name: Email

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dawidd6/action-send-mail@v3.6.0
        with: 
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          to: forcensem2021@gmail.com
          from: Group 3 - Tyler Blackmon and Brittany Hill
